In [12]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [13]:
df = pd.read_csv(r"C:\DataAnalystProjects\Smart-Retail-Demand-Inventory-Analytics\data\raw\retail_store_inventory.csv")

In [14]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [15]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion',
       'Competitor Pricing', 'Seasonality'],
      dtype='str')

In [17]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

In [18]:
df.columns

Index(['date', 'store_id', 'product_id', 'category', 'region',
       'inventory_level', 'units_sold', 'units_ordered', 'demand_forecast',
       'price', 'discount', 'weather_condition', 'holiday_promotion',
       'competitor_pricing', 'seasonality'],
      dtype='str')

In [19]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 73100
Columns: 15

In [20]:
df.dtypes

date                      str
store_id                  str
product_id                str
category                  str
region                    str
inventory_level         int64
units_sold              int64
units_ordered           int64
demand_forecast       float64
price                 float64
discount                int64
weather_condition         str
holiday_promotion       int64
competitor_pricing    float64
seasonality               str
dtype: object

In [21]:
df.isnull().sum()

date                  0
store_id              0
product_id            0
category              0
region                0
inventory_level       0
units_sold            0
units_ordered         0
demand_forecast       0
price                 0
discount              0
weather_condition     0
holiday_promotion     0
competitor_pricing    0
seasonality           0
dtype: int64

In [22]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [23]:
df = df.drop_duplicates()

In [24]:
df.shape

(73100, 15)

In [25]:
df["category"].unique()

<StringArray>
['Groceries', 'Toys', 'Electronics', 'Furniture', 'Clothing']
Length: 5, dtype: str

In [26]:
df["region"].unique()

<StringArray>
['North', 'South', 'West', 'East']
Length: 4, dtype: str

In [27]:
df["weather_condition"].unique()

<StringArray>
['Rainy', 'Sunny', 'Cloudy', 'Snowy']
Length: 4, dtype: str

In [28]:
df["seasonality"].unique()

<StringArray>
['Autumn', 'Summer', 'Winter', 'Spring']
Length: 4, dtype: str

In [29]:
numeric_cols = [
    "inventory_level",
    "units_sold",
    "units_ordered",
    "demand_forecast",
    "price",
    "discount",
    "competitor_pricing"
]

df[numeric_cols].describe()

,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,competitor_pricing
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,10.009508,55.146077
std,129.949514,108.919406,52.277448,109.254076,26.021945,7.083746,26.191408
min,50.000000,0.000000,20.000000,-9.990000,10.000000,0.000000,5.030000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,5.000000,32.680000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,10.000000,55.010000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,15.000000,77.820000
max,500.000000,499.000000,200.000000,518.550000,100.000000,20.000000,104.940000

In [30]:
(df[numeric_cols] < 0).sum()

inventory_level         0
units_sold              0
units_ordered           0
demand_forecast       673
price                   0
discount                0
competitor_pricing      0
dtype: int64

In [31]:
df["revenue"] = df["units_sold"] * df["price"]

In [32]:
df[["units_sold", "price", "revenue"]].head()

   units_sold  price  revenue
0         127  33.50  4254.50
1         150  63.01  9451.50
2          65  27.99  1819.35
3          61  32.72  1995.92
4          14  73.64  1030.96

In [33]:
df.head()

,date,store_id,product_id,category,region,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,weather_condition,holiday_promotion,competitor_pricing,seasonality,revenue
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,4254.50
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,9451.50
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,1819.35
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,1995.92
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,1030.96

In [34]:
import os

os.makedirs("outputs", exist_ok=True)

In [35]:
df.to_csv("outputs/cleaned_data.csv", index=False)

print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

In [36]:
print(df.shape)

(73100, 16)