In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("outputs/cleaned_data.csv")

inventory_df = pd.read_csv("outputs/inventory_analysis.csv")

df.head()

,date,store_id,product_id,category,region,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,weather_condition,holiday_promotion,competitor_pricing,seasonality,revenue
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,4254.50
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,9451.50
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,1819.35
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,1995.92
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,1030.96

In [3]:
df["revenue"] = (
    df["units_sold"]
    *
    df["price"]
)

In [4]:
df["forecast_error"] = (
    df["units_sold"]
    -
    df["demand_forecast"]
)

In [5]:
df["forecast_accuracy"] = (
    1 -
    (
        abs(df["forecast_error"])
        /
        (df["units_sold"] + 1)
    )
) * 100

In [6]:
dashboard_df = pd.merge(
    df,
    inventory_df[
        [
            "product_id",
            "abc_class",
            "risk_status"
        ]
    ],
    on="product_id",
    how="left"
)

In [7]:
dashboard_df.head()

,date,store_id,product_id,category,region,inventory_level,units_sold,units_ordered,demand_forecast,price,discount,weather_condition,holiday_promotion,competitor_pricing,seasonality,revenue,forecast_error,forecast_accuracy,abc_class,risk_status
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,4254.50,-8.47,93.382812,A,MEDIUM RISK
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn,9451.50,5.96,96.052980,C,SAFE
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer,1819.35,-9.02,86.333333,B,SAFE
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn,1995.92,-1.18,98.096774,A,HIGH RISK
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer,1030.96,4.74,68.400000,A,HIGH RISK

In [8]:
dashboard_df.shape

(73100, 20)

In [9]:
dashboard_df.to_csv(
    "outputs/dashboard_dataset.csv",
    index=False
)

print("Dashboard Dataset Saved")

Dashboard Dataset Saved

In [10]:
dashboard_df.columns

Index(['date', 'store_id', 'product_id', 'category', 'region',
       'inventory_level', 'units_sold', 'units_ordered', 'demand_forecast',
       'price', 'discount', 'weather_condition', 'holiday_promotion',
       'competitor_pricing', 'seasonality', 'revenue', 'forecast_error',
       'forecast_accuracy', 'abc_class', 'risk_status'],
      dtype='str')